---

computername: Stark
hostname: stark

finder_proxy_icon_hover_delay: 0

safari_show_full_url_in_address_bar: true
safari_open_safe_files_automatically: true
safari_show_status_bar: true
safari_show_developer_menu: true

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

homebrew_taps:
  - adoptopenjdk/openjdk
  - filledstacks/tap
  - homebrew/bundle
  - homebrew/cask-fonts
  - homebrew/services
  - qmk/qmk

homebrew_apps:
  - alacritty
  - amethyst
  - audacity
  - brave-browser
  - calibre
  - discord # Voice and text chat software
  # - dropbox
  # - firefox
  # - font-fira-code
  # - font-fira-code-nerd-font
  # - font-hasklig
  # - font-iosevka-nerd-font
  - font-jetbrains-mono-nerd-font
  # - font-victor-mono-nerd-font
  - google-chrome
  - grammarly
  - hammerspoon
  - handbrake
  - http-toolkit
  - iina
  # - inkscape
  - insomnia
  # - intel-haxm
  - karabiner-elements
  - keycastr
  - marta
  # - ngrok
  - opera
  # - oracle-jdk
  # - qmk-toolbox
  - rar
  - raycast
  - slack # Team communication and collaboration software
  - spaceman
  - spotify # Music streaming service
  - stats
  # - tandem
  - telegram # Messaging app with a focus on speed and security
  # - transmission
  - vial
  - visual-studio-code
  # - vnc-viewer
  - vox
  - wezterm
  - whatsapp # Desktop client for WhatsApp
  # - wireshark
  # - x2goclient

homebrew_packages:
  - asdf
  - bash
  - bat
  - eza # A modern, maintained replacement for ls
  - fd
  - ffmpeg
  - flutter
  - fzf
  - gawk
  - gcc
  - git
  - git-delta
  - glow # Render markdown on the CLI
  - gnupg
  - gnu-sed
  - htop
  - imagemagick
  - irssi
  - openjdk
  - jq # Lightweight and flexible command-line JSON processor
  - lazygit
  - lcov
  - lf
  - lsd # The next gen ls command
  - lua
  - luajit
  - luarocks
  - make
  - mas # Mac App Store command-line interface
  - ncdu
  - neovim
  # - nmap
  - npm
  - prettier
  - ripgrep
  - shellcheck
  - starship
  - stylua
  - tldr
  - tmux
  - tokei
  - translate-shell
  - w3m
  - wget
  - yarn
  - you-get
  - z
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-syntax-highlighting
  - filledstacks/tap/sessionmate
  - qmk/qmk/qmk

mas_apps:
  - { name: Bitwarden, id: 1352778147 }
  # - { name: Cinebench, id: 1438772273 }
  - { name: Flow, id: 1423210932 }
  # - { name: Spark, id: 1176895641 }
  # - { name: Tomito, id: 1526042938 }
  - { name: Xcode, id: 497799835 }